export function getMDXComponents(_content: string): Record<string, any> {
  throw new Error(
    '[rari/mdx] Client component registry is generated by the rari vite plugin. '
    + 'Use evaluate from "rari/mdx" in a project using the rari() plugin.',
  )
}
