//! React ESM bundles for server-side HTML rendering (Fizz).
//!
//! These are pre-bundled ESM versions of React's CJS production builds,
//! generated by `tools/bundle-react-esm/bundle.ts` (run via `just
//! bundle-react-esm`) and emitted into the rari extension for snapshotting.
//!
//! Used in HTML rendering contexts where we need React's actual reconciler and
//! `renderToReadableStream` (Fizz). The module loader resolves bare `react`
//! imports to `ext:rari/react/vendor/*`, which are registered as
//! `lazy_loaded_esm` and loaded via `core.createLazyLoader` / `op_lazy_load_esm`.
//!
//! Explicit vendor setup (Fizz/RSC pipeline) goes through
//! `ext:rari/react/vendor_loaders.ts`.

pub const REACT_ESM: &str = include_str!("../ext/rari/react/vendor/react.js");

pub const REACT_DOM_ESM: &str = include_str!("../ext/rari/react/vendor/react-dom.js");

pub const REACT_JSX_RUNTIME_ESM: &str =
    include_str!("../ext/rari/react/vendor/react-jsx-runtime.js");

pub const REACT_SERVER_ESM: &str = include_str!("../ext/rari/react/vendor/react-server.js");

pub const REACT_DOM_SERVER_ESM: &str = include_str!("../ext/rari/react/vendor/react-dom-server.js");

pub const REACT_FLIGHT_CLIENT_ESM: &str =
    include_str!("../ext/rari/react/vendor/react-server-dom-webpack-client.js");

pub const REACT_FLIGHT_SERVER_ESM: &str =
    include_str!("../ext/rari/react/vendor/react-server-dom-webpack-server.js");
