use std::{
    env,
    fmt::Write,
    fs,
    path::{Path, PathBuf},
    ptr,
    rc::Rc,
    string::String,
};

use deno_ast::MediaType;
use deno_core::{ModuleCodeString, ModuleName, SourceMapData, snapshot, v8};
use deno_error::JsErrorBox;
use deno_node::{ContextInitMode, VM_CONTEXT_INDEX, create_v8_context, init_global_template};
use rari::runtime::{
    ext::{self, ExtensionOptions},
    transpile,
};
use rustc_hash::FxHashSet;

type Transpiler = dyn Fn(
    ModuleName,
    ModuleCodeString,
) -> Result<(ModuleCodeString, Option<SourceMapData>), JsErrorBox>;

#[expect(clippy::too_many_lines, clippy::cast_precision_loss)]
fn main() {
    let output_dir = env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("crates/rari/snapshots"));

    #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
    fs::create_dir_all(&output_dir).expect("Failed to create output directory");

    let snapshot_path = output_dir.join("RARI_SNAPSHOT.bin");
    let residual_path = output_dir.join("residual_lazy_sources.rs");

    #[expect(clippy::print_stdout, reason = "CLI tool - stdout output is expected")]
    {
        println!("Building V8 snapshot...");
    }

    let ext_options = ExtensionOptions::default();
    let extensions = ext::extensions(&ext_options, false);

    let transpiler: Rc<Transpiler> =
        Rc::new(|name, source| transpile::maybe_transpile_source(&name, source));

    #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
    let output = snapshot::create_snapshot(
        snapshot::CreateSnapshotOptions {
            cargo_manifest_dir: env!("CARGO_MANIFEST_DIR"),
            startup_snapshot: None,
            skip_op_registration: false,
            extensions,
            extension_transpiler: Some(transpiler),
            with_runtime_cb: Some(Box::new(|rt| {
                let isolate = rt.v8_isolate();
                v8::scope!(scope, isolate);

                let tmpl = init_global_template(scope, ContextInitMode::ForSnapshot);
                let ctx =
                    create_v8_context(scope, tmpl, ContextInitMode::ForSnapshot, ptr::null_mut());
                assert_eq!(scope.add_context(ctx), VM_CONTEXT_INDEX);
            })),
        },
        None,
    )
    .expect("Failed to create V8 snapshot");

    #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
    fs::write(&snapshot_path, &output.output).expect("Failed to write snapshot file");
    #[expect(clippy::print_stdout, reason = "CLI tool - stdout output is expected")]
    {
        println!(
            "Snapshot written to {} ({:.2} MB)",
            snapshot_path.display(),
            output.output.len() as f64 / 1024.0 / 1024.0
        );
    }

    let consumed: FxHashSet<&str> =
        output.consumed_lazy_specifiers.iter().map(String::as_str).collect();

    #[expect(clippy::print_stdout, reason = "CLI tool - stdout output is expected")]
    {
        println!("Consumed {} lazy specifiers during snapshot creation", consumed.len());
    }

    let ext_options = ExtensionOptions::default();
    let extensions = ext::extensions(&ext_options, false);

    let mut residual_esm = Vec::new();
    let mut residual_js = Vec::new();

    for ext in &extensions {
        for file in ext.lazy_loaded_esm_files.iter() {
            if !consumed.contains(file.specifier)
                && let Ok(source) = file.load()
            {
                let source = maybe_transpile(file.specifier, &source);
                residual_esm.push((file.specifier, source));
            }
        }
        for file in ext.lazy_loaded_js_files.iter() {
            if !consumed.contains(file.specifier)
                && let Ok(source) = file.load()
            {
                let source = maybe_transpile(file.specifier, &source);
                residual_js.push((file.specifier, source));
            }
        }
    }

    #[expect(clippy::print_stdout, reason = "CLI tool - stdout output is expected")]
    {
        println!("Residual lazy sources: {} ESM, {} JS", residual_esm.len(), residual_js.len());
    }

    let mut generated = String::new();
    write_line(&mut generated, "// Auto-generated by tools/snapshot - do not edit");
    write_line(
        &mut generated,
        "// Residual lazy-loaded sources not consumed during snapshot creation\n",
    );

    write_line(&mut generated, "pub static RESIDUAL_LAZY_ESM_SOURCES: &[(&str, &str)] = &[");
    for (specifier, source) in &residual_esm {
        let specifier_raw = format_raw_string(specifier);
        let source_raw = format_raw_string(source);
        write_line(&mut generated, &format!("    ({specifier_raw}, {source_raw}),"));
    }
    write_line(&mut generated, "];\n");

    write_line(&mut generated, "pub static RESIDUAL_LAZY_JS_SOURCES: &[(&str, &str)] = &[");
    for (specifier, source) in &residual_js {
        let specifier_raw = format_raw_string(specifier);
        let source_raw = format_raw_string(source);
        write_line(&mut generated, &format!("    ({specifier_raw}, {source_raw}),"));
    }
    write_line(&mut generated, "];");

    #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
    fs::write(&residual_path, &generated).expect("Failed to write residual sources");
    #[expect(clippy::print_stdout, reason = "CLI tool - stdout output is expected")]
    {
        println!("Residual sources written to {}", residual_path.display());
        println!("Files loaded during snapshot: {}", output.files_loaded_during_snapshot.len());
    }
}

fn write_line(buf: &mut String, line: &str) {
    #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
    writeln!(buf, "{line}").expect("Failed to write to string buffer");
}

fn maybe_transpile(specifier: &str, source: &str) -> String {
    let source = transpile::substitute_version_placeholders_in_source(source);

    let media_type = if specifier.starts_with("node:") {
        MediaType::TypeScript
    } else {
        MediaType::from_path(Path::new(specifier))
    };

    match media_type {
        MediaType::TypeScript | MediaType::Tsx | MediaType::Jsx => {}
        _ => return source,
    }

    let specifier_url = url::Url::parse(specifier).unwrap_or_else(|_| {
        #[expect(clippy::expect_used, reason = "Infallible operation with valid inputs")]
        url::Url::parse(&format!("file:///{specifier}")).expect("invalid specifier")
    });

    #[expect(
        clippy::panic,
        reason = "Build tool - parse failures should terminate snapshot generation"
    )]
    let parsed = deno_ast::parse_module(deno_ast::ParseParams {
        specifier: specifier_url,
        text: source.into(),
        media_type,
        capture_tokens: false,
        scope_analysis: false,
        maybe_syntax: None,
    })
    .unwrap_or_else(|e| panic!("Failed to parse '{specifier}': {e}"));

    #[expect(
        clippy::panic,
        reason = "Build tool - transpile failures should terminate snapshot generation"
    )]
    let transpiled = parsed
        .transpile(
            &deno_ast::TranspileOptions {
                imports_not_used_as_values: deno_ast::ImportsNotUsedAsValues::Remove,
                ..Default::default()
            },
            &deno_ast::TranspileModuleOptions::default(),
            &deno_ast::EmitOptions {
                source_map: deno_ast::SourceMapOption::None,
                ..Default::default()
            },
        )
        .unwrap_or_else(|e| panic!("Failed to transpile '{specifier}': {e}"));

    transpiled.into_source().text
}

fn min_hashes_needed(s: &str) -> usize {
    let mut max_hashes = 0;
    let mut current_hashes = 0;
    let mut after_quote = false;

    for ch in s.chars() {
        if ch == '"' {
            after_quote = true;
            current_hashes = 0;
        } else if after_quote && ch == '#' {
            current_hashes += 1;
            max_hashes = max_hashes.max(current_hashes);
        } else {
            after_quote = false;
            current_hashes = 0;
        }
    }

    max_hashes + 1
}

fn format_raw_string(s: &str) -> String {
    let hashes_needed = min_hashes_needed(s);

    let hashes_to_use = if hashes_needed == 1 && !s.contains('"') { 0 } else { hashes_needed };

    let hashes = "#".repeat(hashes_to_use);
    format!("r{hashes}\"{s}\"{hashes}")
}
